package com.aiflow.dashboard.db.dao;

import com.aiflow.dashboard.db.domain.DashboardGoodsAttribute;
import com.aiflow.dashboard.db.domain.DashboardGoodsAttributeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DashboardGoodsAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_attribute
     *
     * @mbg.generated
     */
    long countByExample(DashboardGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByExample(DashboardGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_attribute
     *
     * @mbg.generated
     */
    int insert(DashboardGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_attribute
     *
     * @mbg.generated
     */
    int insertSelective(DashboardGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_attribute
     *
     * @mbg.generated
     */
    DashboardGoodsAttribute selectOneByExample(DashboardGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_attribute
     *
     * @mbg.generated
     */
    DashboardGoodsAttribute selectOneByExampleSelective(@Param("example") DashboardGoodsAttributeExample example, @Param("selective") DashboardGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_attribute
     *
     * @mbg.generated
     */
    List<DashboardGoodsAttribute> selectByExampleSelective(@Param("example") DashboardGoodsAttributeExample example, @Param("selective") DashboardGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_attribute
     *
     * @mbg.generated
     */
    List<DashboardGoodsAttribute> selectByExample(DashboardGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_attribute
     *
     * @mbg.generated
     */
    DashboardGoodsAttribute selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DashboardGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_attribute
     *
     * @mbg.generated
     */
    DashboardGoodsAttribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_attribute
     *
     * @mbg.generated
     */
    DashboardGoodsAttribute selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DashboardGoodsAttribute record, @Param("example") DashboardGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DashboardGoodsAttribute record, @Param("example") DashboardGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DashboardGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DashboardGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DashboardGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}