package com.aiflow.dashboard.db.dao;

import com.aiflow.dashboard.db.domain.DashboardAddress;
import com.aiflow.dashboard.db.domain.DashboardAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DashboardAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_address
     *
     * @mbg.generated
     */
    long countByExample(DashboardAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_address
     *
     * @mbg.generated
     */
    int deleteByExample(DashboardAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_address
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_address
     *
     * @mbg.generated
     */
    int insert(DashboardAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_address
     *
     * @mbg.generated
     */
    int insertSelective(DashboardAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_address
     *
     * @mbg.generated
     */
    DashboardAddress selectOneByExample(DashboardAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_address
     *
     * @mbg.generated
     */
    DashboardAddress selectOneByExampleSelective(@Param("example") DashboardAddressExample example, @Param("selective") DashboardAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_address
     *
     * @mbg.generated
     */
    List<DashboardAddress> selectByExampleSelective(@Param("example") DashboardAddressExample example, @Param("selective") DashboardAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_address
     *
     * @mbg.generated
     */
    List<DashboardAddress> selectByExample(DashboardAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_address
     *
     * @mbg.generated
     */
    DashboardAddress selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DashboardAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_address
     *
     * @mbg.generated
     */
    DashboardAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_address
     *
     * @mbg.generated
     */
    DashboardAddress selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_address
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DashboardAddress record, @Param("example") DashboardAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_address
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DashboardAddress record, @Param("example") DashboardAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DashboardAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DashboardAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_address
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DashboardAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_address
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}