package com.aiflow.dashboard.db.dao;

import com.aiflow.dashboard.db.domain.DashboardUser;
import com.aiflow.dashboard.db.domain.DashboardUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DashboardUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_user
     *
     * @mbg.generated
     */
    long countByExample(DashboardUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_user
     *
     * @mbg.generated
     */
    int deleteByExample(DashboardUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_user
     *
     * @mbg.generated
     */
    int insert(DashboardUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_user
     *
     * @mbg.generated
     */
    int insertSelective(DashboardUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_user
     *
     * @mbg.generated
     */
    DashboardUser selectOneByExample(DashboardUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_user
     *
     * @mbg.generated
     */
    DashboardUser selectOneByExampleSelective(@Param("example") DashboardUserExample example, @Param("selective") DashboardUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_user
     *
     * @mbg.generated
     */
    List<DashboardUser> selectByExampleSelective(@Param("example") DashboardUserExample example, @Param("selective") DashboardUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_user
     *
     * @mbg.generated
     */
    List<DashboardUser> selectByExample(DashboardUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_user
     *
     * @mbg.generated
     */
    DashboardUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DashboardUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_user
     *
     * @mbg.generated
     */
    DashboardUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_user
     *
     * @mbg.generated
     */
    DashboardUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DashboardUser record, @Param("example") DashboardUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DashboardUser record, @Param("example") DashboardUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DashboardUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DashboardUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DashboardUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}