package com.aiflow.dashboard.db.dao;

import com.aiflow.dashboard.db.domain.DashboardCollect;
import com.aiflow.dashboard.db.domain.DashboardCollectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DashboardCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_collect
     *
     * @mbg.generated
     */
    long countByExample(DashboardCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_collect
     *
     * @mbg.generated
     */
    int deleteByExample(DashboardCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_collect
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_collect
     *
     * @mbg.generated
     */
    int insert(DashboardCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_collect
     *
     * @mbg.generated
     */
    int insertSelective(DashboardCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_collect
     *
     * @mbg.generated
     */
    DashboardCollect selectOneByExample(DashboardCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_collect
     *
     * @mbg.generated
     */
    DashboardCollect selectOneByExampleSelective(@Param("example") DashboardCollectExample example, @Param("selective") DashboardCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_collect
     *
     * @mbg.generated
     */
    List<DashboardCollect> selectByExampleSelective(@Param("example") DashboardCollectExample example, @Param("selective") DashboardCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_collect
     *
     * @mbg.generated
     */
    List<DashboardCollect> selectByExample(DashboardCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_collect
     *
     * @mbg.generated
     */
    DashboardCollect selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DashboardCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_collect
     *
     * @mbg.generated
     */
    DashboardCollect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_collect
     *
     * @mbg.generated
     */
    DashboardCollect selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_collect
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DashboardCollect record, @Param("example") DashboardCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_collect
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DashboardCollect record, @Param("example") DashboardCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DashboardCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DashboardCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DashboardCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}