package com.aiflow.dashboard.db.dao;

import com.aiflow.dashboard.db.domain.DashboardGroupon;
import com.aiflow.dashboard.db.domain.DashboardGrouponExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DashboardGrouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon
     *
     * @mbg.generated
     */
    long countByExample(DashboardGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon
     *
     * @mbg.generated
     */
    int deleteByExample(DashboardGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon
     *
     * @mbg.generated
     */
    int insert(DashboardGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon
     *
     * @mbg.generated
     */
    int insertSelective(DashboardGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon
     *
     * @mbg.generated
     */
    DashboardGroupon selectOneByExample(DashboardGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon
     *
     * @mbg.generated
     */
    DashboardGroupon selectOneByExampleSelective(@Param("example") DashboardGrouponExample example, @Param("selective") DashboardGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon
     *
     * @mbg.generated
     */
    List<DashboardGroupon> selectByExampleSelective(@Param("example") DashboardGrouponExample example, @Param("selective") DashboardGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon
     *
     * @mbg.generated
     */
    List<DashboardGroupon> selectByExample(DashboardGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon
     *
     * @mbg.generated
     */
    DashboardGroupon selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DashboardGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon
     *
     * @mbg.generated
     */
    DashboardGroupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon
     *
     * @mbg.generated
     */
    DashboardGroupon selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DashboardGroupon record, @Param("example") DashboardGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DashboardGroupon record, @Param("example") DashboardGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DashboardGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DashboardGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DashboardGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}