package com.aiflow.dashboard.db.dao;

import com.aiflow.dashboard.db.domain.DashboardComment;
import com.aiflow.dashboard.db.domain.DashboardCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DashboardCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_comment
     *
     * @mbg.generated
     */
    long countByExample(DashboardCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_comment
     *
     * @mbg.generated
     */
    int deleteByExample(DashboardCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_comment
     *
     * @mbg.generated
     */
    int insert(DashboardComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_comment
     *
     * @mbg.generated
     */
    int insertSelective(DashboardComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_comment
     *
     * @mbg.generated
     */
    DashboardComment selectOneByExample(DashboardCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_comment
     *
     * @mbg.generated
     */
    DashboardComment selectOneByExampleSelective(@Param("example") DashboardCommentExample example, @Param("selective") DashboardComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_comment
     *
     * @mbg.generated
     */
    List<DashboardComment> selectByExampleSelective(@Param("example") DashboardCommentExample example, @Param("selective") DashboardComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_comment
     *
     * @mbg.generated
     */
    List<DashboardComment> selectByExample(DashboardCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_comment
     *
     * @mbg.generated
     */
    DashboardComment selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DashboardComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_comment
     *
     * @mbg.generated
     */
    DashboardComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_comment
     *
     * @mbg.generated
     */
    DashboardComment selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_comment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DashboardComment record, @Param("example") DashboardCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_comment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DashboardComment record, @Param("example") DashboardCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DashboardComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DashboardComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_comment
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DashboardCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_comment
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}