package com.aiflow.dashboard.db.dao;

import com.aiflow.dashboard.db.domain.DashboardRegion;
import com.aiflow.dashboard.db.domain.DashboardRegionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DashboardRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_region
     *
     * @mbg.generated
     */
    long countByExample(DashboardRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_region
     *
     * @mbg.generated
     */
    int deleteByExample(DashboardRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_region
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_region
     *
     * @mbg.generated
     */
    int insert(DashboardRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_region
     *
     * @mbg.generated
     */
    int insertSelective(DashboardRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_region
     *
     * @mbg.generated
     */
    DashboardRegion selectOneByExample(DashboardRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_region
     *
     * @mbg.generated
     */
    DashboardRegion selectOneByExampleSelective(@Param("example") DashboardRegionExample example, @Param("selective") DashboardRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_region
     *
     * @mbg.generated
     */
    List<DashboardRegion> selectByExampleSelective(@Param("example") DashboardRegionExample example, @Param("selective") DashboardRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_region
     *
     * @mbg.generated
     */
    List<DashboardRegion> selectByExample(DashboardRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_region
     *
     * @mbg.generated
     */
    DashboardRegion selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DashboardRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_region
     *
     * @mbg.generated
     */
    DashboardRegion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_region
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DashboardRegion record, @Param("example") DashboardRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_region
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DashboardRegion record, @Param("example") DashboardRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DashboardRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DashboardRegion record);
}