package com.aiflow.dashboard.db.dao;

import com.aiflow.dashboard.db.domain.DashboardFootprint;
import com.aiflow.dashboard.db.domain.DashboardFootprintExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DashboardFootprintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_footprint
     *
     * @mbg.generated
     */
    long countByExample(DashboardFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_footprint
     *
     * @mbg.generated
     */
    int deleteByExample(DashboardFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_footprint
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_footprint
     *
     * @mbg.generated
     */
    int insert(DashboardFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_footprint
     *
     * @mbg.generated
     */
    int insertSelective(DashboardFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_footprint
     *
     * @mbg.generated
     */
    DashboardFootprint selectOneByExample(DashboardFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_footprint
     *
     * @mbg.generated
     */
    DashboardFootprint selectOneByExampleSelective(@Param("example") DashboardFootprintExample example, @Param("selective") DashboardFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_footprint
     *
     * @mbg.generated
     */
    List<DashboardFootprint> selectByExampleSelective(@Param("example") DashboardFootprintExample example, @Param("selective") DashboardFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_footprint
     *
     * @mbg.generated
     */
    List<DashboardFootprint> selectByExample(DashboardFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_footprint
     *
     * @mbg.generated
     */
    DashboardFootprint selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DashboardFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_footprint
     *
     * @mbg.generated
     */
    DashboardFootprint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_footprint
     *
     * @mbg.generated
     */
    DashboardFootprint selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_footprint
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DashboardFootprint record, @Param("example") DashboardFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_footprint
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DashboardFootprint record, @Param("example") DashboardFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_footprint
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DashboardFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_footprint
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DashboardFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_footprint
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DashboardFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_footprint
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}