package com.aiflow.dashboard.db.dao;

import com.aiflow.dashboard.db.domain.DashboardKeyword;
import com.aiflow.dashboard.db.domain.DashboardKeywordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DashboardKeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_keyword
     *
     * @mbg.generated
     */
    long countByExample(DashboardKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_keyword
     *
     * @mbg.generated
     */
    int deleteByExample(DashboardKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_keyword
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_keyword
     *
     * @mbg.generated
     */
    int insert(DashboardKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_keyword
     *
     * @mbg.generated
     */
    int insertSelective(DashboardKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_keyword
     *
     * @mbg.generated
     */
    DashboardKeyword selectOneByExample(DashboardKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_keyword
     *
     * @mbg.generated
     */
    DashboardKeyword selectOneByExampleSelective(@Param("example") DashboardKeywordExample example, @Param("selective") DashboardKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_keyword
     *
     * @mbg.generated
     */
    List<DashboardKeyword> selectByExampleSelective(@Param("example") DashboardKeywordExample example, @Param("selective") DashboardKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_keyword
     *
     * @mbg.generated
     */
    List<DashboardKeyword> selectByExample(DashboardKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_keyword
     *
     * @mbg.generated
     */
    DashboardKeyword selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DashboardKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_keyword
     *
     * @mbg.generated
     */
    DashboardKeyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_keyword
     *
     * @mbg.generated
     */
    DashboardKeyword selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_keyword
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DashboardKeyword record, @Param("example") DashboardKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_keyword
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DashboardKeyword record, @Param("example") DashboardKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DashboardKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DashboardKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_keyword
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DashboardKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_keyword
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}