package com.aiflow.dashboard.db.dao;

import com.aiflow.dashboard.db.domain.DashboardStorage;
import com.aiflow.dashboard.db.domain.DashboardStorageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DashboardStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_storage
     *
     * @mbg.generated
     */
    long countByExample(DashboardStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_storage
     *
     * @mbg.generated
     */
    int deleteByExample(DashboardStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_storage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_storage
     *
     * @mbg.generated
     */
    int insert(DashboardStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_storage
     *
     * @mbg.generated
     */
    int insertSelective(DashboardStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_storage
     *
     * @mbg.generated
     */
    DashboardStorage selectOneByExample(DashboardStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_storage
     *
     * @mbg.generated
     */
    DashboardStorage selectOneByExampleSelective(@Param("example") DashboardStorageExample example, @Param("selective") DashboardStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_storage
     *
     * @mbg.generated
     */
    List<DashboardStorage> selectByExampleSelective(@Param("example") DashboardStorageExample example, @Param("selective") DashboardStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_storage
     *
     * @mbg.generated
     */
    List<DashboardStorage> selectByExample(DashboardStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_storage
     *
     * @mbg.generated
     */
    DashboardStorage selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DashboardStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_storage
     *
     * @mbg.generated
     */
    DashboardStorage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_storage
     *
     * @mbg.generated
     */
    DashboardStorage selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_storage
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DashboardStorage record, @Param("example") DashboardStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_storage
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DashboardStorage record, @Param("example") DashboardStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DashboardStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DashboardStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DashboardStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}