package com.aiflow.dashboard.db.dao;

import com.aiflow.dashboard.db.domain.DashboardGoodsProduct;
import com.aiflow.dashboard.db.domain.DashboardGoodsProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DashboardGoodsProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_product
     *
     * @mbg.generated
     */
    long countByExample(DashboardGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_product
     *
     * @mbg.generated
     */
    int deleteByExample(DashboardGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_product
     *
     * @mbg.generated
     */
    int insert(DashboardGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_product
     *
     * @mbg.generated
     */
    int insertSelective(DashboardGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_product
     *
     * @mbg.generated
     */
    DashboardGoodsProduct selectOneByExample(DashboardGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_product
     *
     * @mbg.generated
     */
    DashboardGoodsProduct selectOneByExampleSelective(@Param("example") DashboardGoodsProductExample example, @Param("selective") DashboardGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_product
     *
     * @mbg.generated
     */
    List<DashboardGoodsProduct> selectByExampleSelective(@Param("example") DashboardGoodsProductExample example, @Param("selective") DashboardGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_product
     *
     * @mbg.generated
     */
    List<DashboardGoodsProduct> selectByExample(DashboardGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_product
     *
     * @mbg.generated
     */
    DashboardGoodsProduct selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DashboardGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_product
     *
     * @mbg.generated
     */
    DashboardGoodsProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_product
     *
     * @mbg.generated
     */
    DashboardGoodsProduct selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DashboardGoodsProduct record, @Param("example") DashboardGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DashboardGoodsProduct record, @Param("example") DashboardGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DashboardGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DashboardGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DashboardGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}