package com.aiflow.dashboard.db.dao;

import com.aiflow.dashboard.db.domain.DashboardCategory;
import com.aiflow.dashboard.db.domain.DashboardCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DashboardCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_category
     *
     * @mbg.generated
     */
    long countByExample(DashboardCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_category
     *
     * @mbg.generated
     */
    int deleteByExample(DashboardCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_category
     *
     * @mbg.generated
     */
    int insert(DashboardCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_category
     *
     * @mbg.generated
     */
    int insertSelective(DashboardCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_category
     *
     * @mbg.generated
     */
    DashboardCategory selectOneByExample(DashboardCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_category
     *
     * @mbg.generated
     */
    DashboardCategory selectOneByExampleSelective(@Param("example") DashboardCategoryExample example, @Param("selective") DashboardCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_category
     *
     * @mbg.generated
     */
    List<DashboardCategory> selectByExampleSelective(@Param("example") DashboardCategoryExample example, @Param("selective") DashboardCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_category
     *
     * @mbg.generated
     */
    List<DashboardCategory> selectByExample(DashboardCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_category
     *
     * @mbg.generated
     */
    DashboardCategory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DashboardCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_category
     *
     * @mbg.generated
     */
    DashboardCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_category
     *
     * @mbg.generated
     */
    DashboardCategory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DashboardCategory record, @Param("example") DashboardCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DashboardCategory record, @Param("example") DashboardCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DashboardCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DashboardCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_category
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DashboardCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_category
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}