package com.aiflow.dashboard.db.dao;

import com.aiflow.dashboard.db.domain.DashboardFeedback;
import com.aiflow.dashboard.db.domain.DashboardFeedbackExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DashboardFeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_feedback
     *
     * @mbg.generated
     */
    long countByExample(DashboardFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_feedback
     *
     * @mbg.generated
     */
    int deleteByExample(DashboardFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_feedback
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_feedback
     *
     * @mbg.generated
     */
    int insert(DashboardFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_feedback
     *
     * @mbg.generated
     */
    int insertSelective(DashboardFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_feedback
     *
     * @mbg.generated
     */
    DashboardFeedback selectOneByExample(DashboardFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_feedback
     *
     * @mbg.generated
     */
    DashboardFeedback selectOneByExampleSelective(@Param("example") DashboardFeedbackExample example, @Param("selective") DashboardFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_feedback
     *
     * @mbg.generated
     */
    List<DashboardFeedback> selectByExampleSelective(@Param("example") DashboardFeedbackExample example, @Param("selective") DashboardFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_feedback
     *
     * @mbg.generated
     */
    List<DashboardFeedback> selectByExample(DashboardFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_feedback
     *
     * @mbg.generated
     */
    DashboardFeedback selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DashboardFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_feedback
     *
     * @mbg.generated
     */
    DashboardFeedback selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_feedback
     *
     * @mbg.generated
     */
    DashboardFeedback selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_feedback
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DashboardFeedback record, @Param("example") DashboardFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_feedback
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DashboardFeedback record, @Param("example") DashboardFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_feedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DashboardFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_feedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DashboardFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_feedback
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DashboardFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_feedback
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}