package com.aiflow.dashboard.db.dao;

import com.aiflow.dashboard.db.domain.DashboardSystem;
import com.aiflow.dashboard.db.domain.DashboardSystemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DashboardSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_system
     *
     * @mbg.generated
     */
    long countByExample(DashboardSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_system
     *
     * @mbg.generated
     */
    int deleteByExample(DashboardSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_system
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_system
     *
     * @mbg.generated
     */
    int insert(DashboardSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_system
     *
     * @mbg.generated
     */
    int insertSelective(DashboardSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_system
     *
     * @mbg.generated
     */
    DashboardSystem selectOneByExample(DashboardSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_system
     *
     * @mbg.generated
     */
    DashboardSystem selectOneByExampleSelective(@Param("example") DashboardSystemExample example, @Param("selective") DashboardSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_system
     *
     * @mbg.generated
     */
    List<DashboardSystem> selectByExampleSelective(@Param("example") DashboardSystemExample example, @Param("selective") DashboardSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_system
     *
     * @mbg.generated
     */
    List<DashboardSystem> selectByExample(DashboardSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_system
     *
     * @mbg.generated
     */
    DashboardSystem selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DashboardSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_system
     *
     * @mbg.generated
     */
    DashboardSystem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_system
     *
     * @mbg.generated
     */
    DashboardSystem selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_system
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DashboardSystem record, @Param("example") DashboardSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_system
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DashboardSystem record, @Param("example") DashboardSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DashboardSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DashboardSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_system
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DashboardSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_system
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}