package com.aiflow.dashboard.db.dao;

import com.aiflow.dashboard.db.domain.DashboardNotice;
import com.aiflow.dashboard.db.domain.DashboardNoticeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DashboardNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice
     *
     * @mbg.generated
     */
    long countByExample(DashboardNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice
     *
     * @mbg.generated
     */
    int deleteByExample(DashboardNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice
     *
     * @mbg.generated
     */
    int insert(DashboardNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice
     *
     * @mbg.generated
     */
    int insertSelective(DashboardNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice
     *
     * @mbg.generated
     */
    DashboardNotice selectOneByExample(DashboardNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice
     *
     * @mbg.generated
     */
    DashboardNotice selectOneByExampleSelective(@Param("example") DashboardNoticeExample example, @Param("selective") DashboardNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice
     *
     * @mbg.generated
     */
    List<DashboardNotice> selectByExampleSelective(@Param("example") DashboardNoticeExample example, @Param("selective") DashboardNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice
     *
     * @mbg.generated
     */
    List<DashboardNotice> selectByExample(DashboardNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice
     *
     * @mbg.generated
     */
    DashboardNotice selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DashboardNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice
     *
     * @mbg.generated
     */
    DashboardNotice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice
     *
     * @mbg.generated
     */
    DashboardNotice selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DashboardNotice record, @Param("example") DashboardNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DashboardNotice record, @Param("example") DashboardNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DashboardNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DashboardNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DashboardNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}