package com.aiflow.dashboard.db.dao;

import com.aiflow.dashboard.db.domain.DashboardAftersale;
import com.aiflow.dashboard.db.domain.DashboardAftersaleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DashboardAftersaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_aftersale
     *
     * @mbg.generated
     */
    long countByExample(DashboardAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_aftersale
     *
     * @mbg.generated
     */
    int deleteByExample(DashboardAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_aftersale
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_aftersale
     *
     * @mbg.generated
     */
    int insert(DashboardAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_aftersale
     *
     * @mbg.generated
     */
    int insertSelective(DashboardAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_aftersale
     *
     * @mbg.generated
     */
    DashboardAftersale selectOneByExample(DashboardAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_aftersale
     *
     * @mbg.generated
     */
    DashboardAftersale selectOneByExampleSelective(@Param("example") DashboardAftersaleExample example, @Param("selective") DashboardAftersale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_aftersale
     *
     * @mbg.generated
     */
    List<DashboardAftersale> selectByExampleSelective(@Param("example") DashboardAftersaleExample example, @Param("selective") DashboardAftersale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_aftersale
     *
     * @mbg.generated
     */
    List<DashboardAftersale> selectByExample(DashboardAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_aftersale
     *
     * @mbg.generated
     */
    DashboardAftersale selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DashboardAftersale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_aftersale
     *
     * @mbg.generated
     */
    DashboardAftersale selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_aftersale
     *
     * @mbg.generated
     */
    DashboardAftersale selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_aftersale
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DashboardAftersale record, @Param("example") DashboardAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_aftersale
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DashboardAftersale record, @Param("example") DashboardAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_aftersale
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DashboardAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_aftersale
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DashboardAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_aftersale
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DashboardAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_aftersale
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}