package com.aiflow.dashboard.db.dao;

import com.aiflow.dashboard.db.domain.DashboardAdmin;
import com.aiflow.dashboard.db.domain.DashboardAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DashboardAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_admin
     *
     * @mbg.generated
     */
    long countByExample(DashboardAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_admin
     *
     * @mbg.generated
     */
    int deleteByExample(DashboardAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_admin
     *
     * @mbg.generated
     */
    int insert(DashboardAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_admin
     *
     * @mbg.generated
     */
    int insertSelective(DashboardAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_admin
     *
     * @mbg.generated
     */
    DashboardAdmin selectOneByExample(DashboardAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_admin
     *
     * @mbg.generated
     */
    DashboardAdmin selectOneByExampleSelective(@Param("example") DashboardAdminExample example, @Param("selective") DashboardAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_admin
     *
     * @mbg.generated
     */
    List<DashboardAdmin> selectByExampleSelective(@Param("example") DashboardAdminExample example, @Param("selective") DashboardAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_admin
     *
     * @mbg.generated
     */
    List<DashboardAdmin> selectByExample(DashboardAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_admin
     *
     * @mbg.generated
     */
    DashboardAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DashboardAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_admin
     *
     * @mbg.generated
     */
    DashboardAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_admin
     *
     * @mbg.generated
     */
    DashboardAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DashboardAdmin record, @Param("example") DashboardAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DashboardAdmin record, @Param("example") DashboardAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DashboardAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DashboardAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DashboardAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}