package com.aiflow.dashboard.db.dao;

import com.aiflow.dashboard.db.domain.DashboardCouponUser;
import com.aiflow.dashboard.db.domain.DashboardCouponUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DashboardCouponUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon_user
     *
     * @mbg.generated
     */
    long countByExample(DashboardCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon_user
     *
     * @mbg.generated
     */
    int deleteByExample(DashboardCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon_user
     *
     * @mbg.generated
     */
    int insert(DashboardCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon_user
     *
     * @mbg.generated
     */
    int insertSelective(DashboardCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon_user
     *
     * @mbg.generated
     */
    DashboardCouponUser selectOneByExample(DashboardCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon_user
     *
     * @mbg.generated
     */
    DashboardCouponUser selectOneByExampleSelective(@Param("example") DashboardCouponUserExample example, @Param("selective") DashboardCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon_user
     *
     * @mbg.generated
     */
    List<DashboardCouponUser> selectByExampleSelective(@Param("example") DashboardCouponUserExample example, @Param("selective") DashboardCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon_user
     *
     * @mbg.generated
     */
    List<DashboardCouponUser> selectByExample(DashboardCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon_user
     *
     * @mbg.generated
     */
    DashboardCouponUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DashboardCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon_user
     *
     * @mbg.generated
     */
    DashboardCouponUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon_user
     *
     * @mbg.generated
     */
    DashboardCouponUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DashboardCouponUser record, @Param("example") DashboardCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DashboardCouponUser record, @Param("example") DashboardCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DashboardCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DashboardCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DashboardCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}