package com.aiflow.dashboard.db.dao;

import com.aiflow.dashboard.db.domain.DashboardNoticeAdmin;
import com.aiflow.dashboard.db.domain.DashboardNoticeAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DashboardNoticeAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice_admin
     *
     * @mbg.generated
     */
    long countByExample(DashboardNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice_admin
     *
     * @mbg.generated
     */
    int deleteByExample(DashboardNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice_admin
     *
     * @mbg.generated
     */
    int insert(DashboardNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice_admin
     *
     * @mbg.generated
     */
    int insertSelective(DashboardNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice_admin
     *
     * @mbg.generated
     */
    DashboardNoticeAdmin selectOneByExample(DashboardNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice_admin
     *
     * @mbg.generated
     */
    DashboardNoticeAdmin selectOneByExampleSelective(@Param("example") DashboardNoticeAdminExample example, @Param("selective") DashboardNoticeAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice_admin
     *
     * @mbg.generated
     */
    List<DashboardNoticeAdmin> selectByExampleSelective(@Param("example") DashboardNoticeAdminExample example, @Param("selective") DashboardNoticeAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice_admin
     *
     * @mbg.generated
     */
    List<DashboardNoticeAdmin> selectByExample(DashboardNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice_admin
     *
     * @mbg.generated
     */
    DashboardNoticeAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DashboardNoticeAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice_admin
     *
     * @mbg.generated
     */
    DashboardNoticeAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice_admin
     *
     * @mbg.generated
     */
    DashboardNoticeAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DashboardNoticeAdmin record, @Param("example") DashboardNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DashboardNoticeAdmin record, @Param("example") DashboardNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DashboardNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DashboardNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DashboardNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_notice_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}