package com.aiflow.dashboard.db.dao;

import com.aiflow.dashboard.db.domain.DashboardGrouponRules;
import com.aiflow.dashboard.db.domain.DashboardGrouponRulesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DashboardGrouponRulesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon_rules
     *
     * @mbg.generated
     */
    long countByExample(DashboardGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon_rules
     *
     * @mbg.generated
     */
    int deleteByExample(DashboardGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon_rules
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon_rules
     *
     * @mbg.generated
     */
    int insert(DashboardGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon_rules
     *
     * @mbg.generated
     */
    int insertSelective(DashboardGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon_rules
     *
     * @mbg.generated
     */
    DashboardGrouponRules selectOneByExample(DashboardGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon_rules
     *
     * @mbg.generated
     */
    DashboardGrouponRules selectOneByExampleSelective(@Param("example") DashboardGrouponRulesExample example, @Param("selective") DashboardGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon_rules
     *
     * @mbg.generated
     */
    List<DashboardGrouponRules> selectByExampleSelective(@Param("example") DashboardGrouponRulesExample example, @Param("selective") DashboardGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon_rules
     *
     * @mbg.generated
     */
    List<DashboardGrouponRules> selectByExample(DashboardGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon_rules
     *
     * @mbg.generated
     */
    DashboardGrouponRules selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DashboardGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon_rules
     *
     * @mbg.generated
     */
    DashboardGrouponRules selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon_rules
     *
     * @mbg.generated
     */
    DashboardGrouponRules selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon_rules
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DashboardGrouponRules record, @Param("example") DashboardGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon_rules
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DashboardGrouponRules record, @Param("example") DashboardGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DashboardGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DashboardGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon_rules
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DashboardGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_groupon_rules
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}