package com.aiflow.dashboard.db.dao;

import com.aiflow.dashboard.db.domain.DashboardCart;
import com.aiflow.dashboard.db.domain.DashboardCartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DashboardCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_cart
     *
     * @mbg.generated
     */
    long countByExample(DashboardCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_cart
     *
     * @mbg.generated
     */
    int deleteByExample(DashboardCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_cart
     *
     * @mbg.generated
     */
    int insert(DashboardCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_cart
     *
     * @mbg.generated
     */
    int insertSelective(DashboardCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_cart
     *
     * @mbg.generated
     */
    DashboardCart selectOneByExample(DashboardCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_cart
     *
     * @mbg.generated
     */
    DashboardCart selectOneByExampleSelective(@Param("example") DashboardCartExample example, @Param("selective") DashboardCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_cart
     *
     * @mbg.generated
     */
    List<DashboardCart> selectByExampleSelective(@Param("example") DashboardCartExample example, @Param("selective") DashboardCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_cart
     *
     * @mbg.generated
     */
    List<DashboardCart> selectByExample(DashboardCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_cart
     *
     * @mbg.generated
     */
    DashboardCart selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DashboardCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_cart
     *
     * @mbg.generated
     */
    DashboardCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_cart
     *
     * @mbg.generated
     */
    DashboardCart selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_cart
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DashboardCart record, @Param("example") DashboardCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_cart
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DashboardCart record, @Param("example") DashboardCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DashboardCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DashboardCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DashboardCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}