package com.aiflow.dashboard.db.dao;

import com.aiflow.dashboard.db.domain.DashboardAd;
import com.aiflow.dashboard.db.domain.DashboardAdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DashboardAdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_ad
     *
     * @mbg.generated
     */
    long countByExample(DashboardAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_ad
     *
     * @mbg.generated
     */
    int deleteByExample(DashboardAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_ad
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_ad
     *
     * @mbg.generated
     */
    int insert(DashboardAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_ad
     *
     * @mbg.generated
     */
    int insertSelective(DashboardAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_ad
     *
     * @mbg.generated
     */
    DashboardAd selectOneByExample(DashboardAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_ad
     *
     * @mbg.generated
     */
    DashboardAd selectOneByExampleSelective(@Param("example") DashboardAdExample example, @Param("selective") DashboardAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_ad
     *
     * @mbg.generated
     */
    List<DashboardAd> selectByExampleSelective(@Param("example") DashboardAdExample example, @Param("selective") DashboardAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_ad
     *
     * @mbg.generated
     */
    List<DashboardAd> selectByExample(DashboardAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_ad
     *
     * @mbg.generated
     */
    DashboardAd selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DashboardAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_ad
     *
     * @mbg.generated
     */
    DashboardAd selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_ad
     *
     * @mbg.generated
     */
    DashboardAd selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_ad
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DashboardAd record, @Param("example") DashboardAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_ad
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DashboardAd record, @Param("example") DashboardAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DashboardAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DashboardAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_ad
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DashboardAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_ad
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}