package com.aiflow.dashboard.db.dao;

import com.aiflow.dashboard.db.domain.DashboardBrand;
import com.aiflow.dashboard.db.domain.DashboardBrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DashboardBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_brand
     *
     * @mbg.generated
     */
    long countByExample(DashboardBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_brand
     *
     * @mbg.generated
     */
    int deleteByExample(DashboardBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_brand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_brand
     *
     * @mbg.generated
     */
    int insert(DashboardBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_brand
     *
     * @mbg.generated
     */
    int insertSelective(DashboardBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_brand
     *
     * @mbg.generated
     */
    DashboardBrand selectOneByExample(DashboardBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_brand
     *
     * @mbg.generated
     */
    DashboardBrand selectOneByExampleSelective(@Param("example") DashboardBrandExample example, @Param("selective") DashboardBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_brand
     *
     * @mbg.generated
     */
    List<DashboardBrand> selectByExampleSelective(@Param("example") DashboardBrandExample example, @Param("selective") DashboardBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_brand
     *
     * @mbg.generated
     */
    List<DashboardBrand> selectByExample(DashboardBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_brand
     *
     * @mbg.generated
     */
    DashboardBrand selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DashboardBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_brand
     *
     * @mbg.generated
     */
    DashboardBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_brand
     *
     * @mbg.generated
     */
    DashboardBrand selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_brand
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DashboardBrand record, @Param("example") DashboardBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_brand
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DashboardBrand record, @Param("example") DashboardBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DashboardBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DashboardBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DashboardBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}