package com.aiflow.dashboard.db.dao;

import com.aiflow.dashboard.db.domain.DashboardCoupon;
import com.aiflow.dashboard.db.domain.DashboardCouponExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DashboardCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon
     *
     * @mbg.generated
     */
    long countByExample(DashboardCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon
     *
     * @mbg.generated
     */
    int deleteByExample(DashboardCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon
     *
     * @mbg.generated
     */
    int insert(DashboardCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon
     *
     * @mbg.generated
     */
    int insertSelective(DashboardCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon
     *
     * @mbg.generated
     */
    DashboardCoupon selectOneByExample(DashboardCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon
     *
     * @mbg.generated
     */
    DashboardCoupon selectOneByExampleSelective(@Param("example") DashboardCouponExample example, @Param("selective") DashboardCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon
     *
     * @mbg.generated
     */
    List<DashboardCoupon> selectByExampleSelective(@Param("example") DashboardCouponExample example, @Param("selective") DashboardCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon
     *
     * @mbg.generated
     */
    List<DashboardCoupon> selectByExample(DashboardCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon
     *
     * @mbg.generated
     */
    DashboardCoupon selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DashboardCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon
     *
     * @mbg.generated
     */
    DashboardCoupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon
     *
     * @mbg.generated
     */
    DashboardCoupon selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DashboardCoupon record, @Param("example") DashboardCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DashboardCoupon record, @Param("example") DashboardCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DashboardCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DashboardCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DashboardCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard_coupon
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}